# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9abc9153a8d0e7a2fc01226598152fb2a308e4aa079346819705173a8172ddd126773d35bcc2287dab99225ebee1a80f554d30b4362491b53ab65bec2d89dc4c

test:
  secret_key_base: 966da9d24d508b6add68ef2dffdc54d7f1385839a3a2abe49084a80137168c72c7eb835f7083939d8fc9a710a82bcfafe2d1477683bf711e291dd8f2cad379c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
